export const MOCK_FEED_POSTS = [
  {
    id: 'mincifra-1',
    text: 'В «белый список» включены новые сервисы',
    date: '2024-02-05T09:00:00.000Z',
    channel: 'Минцифры',
    channelUsername: 'mincifra',
    channelId: 'manual',
    link: 'https://t.me/mincifra',
    tema: ['новости', 'сервисы'],
    tags: ['минцифры'],
  },
  {
    id: 'mincifra-2',
    text: 'В 2025 году более 5,4 млн абонентов сменили оператора, сохранив свой номер',
    date: '2024-02-05T09:05:00.000Z',
    channel: 'Минцифры',
    channelUsername: 'mincifra',
    channelId: 'manual',
    link: 'https://t.me/mincifra',
    tema: ['связь', 'операторы'],
    tags: ['минцифры'],
  },
  {
    id: 'mincifra-3',
    text: 'ИТ-специалисты могут подать заявление на отсрочку',
    date: '2024-02-05T09:10:00.000Z',
    channel: 'Минцифры',
    channelUsername: 'mincifra',
    channelId: 'manual',
    link: 'https://t.me/mincifra',
    tema: ['it', 'отсрочка'],
    tags: ['минцифры'],
  },
  {
    id: 'academy-1',
    text: 'Стартовал первый в этом году поток программы «Социальные координаторы»',
    date: '2024-02-05T10:30:00.000Z',
    channel: 'Президентская академия. Новости',
    channelUsername: 'ranepa_news',
    channelId: 'manual',
    link: 'https://t.me/ranepa_news',
    tema: ['академия', 'социальные'],
    tags: ['новости'],
  },
  {
    id: 'moscow-1',
    text: 'Московская музейная неделя',
    date: '2024-02-05T11:00:00.000Z',
    channel: 'Город Москва',
    channelUsername: 'moscow',
    channelId: 'manual',
    link: 'https://t.me/moscow',
    tema: ['город', 'музеи'],
    tags: ['афиша'],
  },
];
