export const MOCK_FEED_POSTS = [
  {
    id: 'mincifra-1',
    text: 'В «белый список» включены новые сервисы',
    date: '2024-01-16T09:00:00.000Z',
    channel: 'Минцифры',
    channelUsername: 'mincifra',
    channelId: 'manual',
    link: 'https://t.me/mincifra',
    tema: ['новости', 'сервисы'],
    tags: ['минцифры'],
  },
  {
    id: 'mincifra-2',
    text: 'В 2025 году более 5,4 млн абонентов сменили оператора, сохранив свой номер',
    date: '2024-01-16T09:05:00.000Z',
    channel: 'Минцифры',
    channelUsername: 'mincifra',
    channelId: 'manual',
    link: 'https://t.me/mincifra',
    tema: ['связь', 'операторы'],
    tags: ['минцифры'],
  },
  {
    id: 'mincifra-3',
    text: 'ИТ-специалисты могут подать заявление на отсрочку',
    date: '2024-01-16T09:10:00.000Z',
    channel: 'Минцифры',
    channelUsername: 'mincifra',
    channelId: 'manual',
    link: 'https://t.me/mincifra',
    tema: ['it', 'отсрочка'],
    tags: ['минцифры'],
  },
];
